services:
  web:
    build:
      dockerfile: ./Dockerfile.dev
    command: bash -c "bundle && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    environment:
      - HISTFILE=.bash_history
      # Replace my_app_
      - DATABASE_URL=postgres://postgres:password@db:5432/wallaby_demo_${RAILS_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      # Replace my_app_
      POSTGRES_DB: wallaby_demo_${RAILS_ENV:-development}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
